sampler:
  _target_: vgs.models.vgsampler.ValueGradientSampler
  value:
    _target_: vgs.models.modules_temb.FCNet_temb
    in_dim: 2
    out_dim: 1
    hidden_dim: 1024
    t_emb_dim: 1024
    activation: relu
    spec_norm: False
  n_step: 20
  sample_shape: [2]
  s2_schedule: quad
  s2_start: 0.2
  s2_end: 0.1
  alpha_method: vp
  tau: 1
  ema: 0.9
  v_lr: 1e-4
  i_lr: 1e-3


buffer:
  n_update: 1


energy_model:
  _target_: vgs.energy.gauss.GMM
  name: "grid"

training:
  n_iter: 3000
  batch_size: 128
  save_iter: 300
  log_iter: 50
  n_eval: 1e5

off_policy:
  noise_scale: 1.2

seed: 0